---
title: "Medium scale data"
subtitle: "An introduction to SQL"
author: "CSC/ST 442"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, metropolis, metropolis-fonts]
    nature:
      highlightStyle: zenburn
      highlightLines: true
      countIncrementalSlides: false
    df_print: tibble

--- 
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.retina = 3, fig.asp = 0.6, fig.align = 'center', out.width = "120%", warning = FALSE, message = FALSE)
options(htmltools.dir.version = FALSE, digits = 3, knitr.table.format = "html",tibble.print_min=6)
```

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
library(tidyverse)
# duo_accent(primary_color = "#006747", secondary_color = "#CFC493",
#   title_slide_background_color = "#FFFFFF",
#   title_slide_text_color = "#006747",
#   header_font_google = google_font("Josefin Sans"),
#   title_slide_background_image = "ncstate.png",
#   title_slide_background_size = "600px",
#   title_slide_background_position = "bottom",
#   text_font_google   = google_font("Montserrat", "300", "300i"),
#   code_font_family = "Fira Code",
#   code_font_url = "https://cdn.rawgit.com/tonsky/FiraCode/1.204/distr/fira_code.css"
# )
# duo(primary_color = "#1F4257", secondary_color = "#F97B64",
#   text_font_google   = google_font("Montserrat", "300", "300i"),
#   code_font_family = "Fira Code",
#   code_font_url = "https://cdn.rawgit.com/tonsky/FiraCode/1.204/distr/fira_code.css"
# )
```
# Introduction to SQL
```{r cache = TRUE}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "airlines")
class(db)
dbListTables(db)
tables <- c("flights", "planes", "airports", "carriers")
nrow.tables <- map_int(tables, function(x) 
  as.integer(db %>% dbGetQuery(paste0("SELECT COUNT(*) FROM ", x))))
names(nrow.tables) <- tables
nrow.tables
```

---
class: clear
```{r cache = TRUE}
flights_db <- db %>% tbl("flights")
tailnum_delay_db <- flights_db %>% 
  group_by(tailnum) %>%
  summarise(
    delay = mean(arr_delay),
    n = n()
  ) %>% 
  arrange(desc(delay)) %>%
  filter(n > 100)
tailnum_delay_db
```
---
class: clear
```{r cache = TRUE}
tailnum_delay_db %>% show_query()
```

raw <- readr::read_csv(lcl, col_names = FALSE,
col_types = cols(
X1 = col_double(),
X2 = col_character(),
                  X3 = col_character(),
                  X4 = col_character(),
                  X5 = col_character(),
                  X6 = col_character(),
                  X7 = col_double(),
                  X8 = col_double(),
                  X9 = col_double(),
                  X10 = col_character(),
                  X11 = col_character(),
                  X12 = col_character(),
                  X13 = col_character(),
                  X14 = col_character()))
raw <- raw[,-c("X13","X14)]
